const data = [
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2021,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: `Juriste d'entreprise`,
  },
  {
    prenom: 'david',
    nom: 'the flower',
    promo: 'college de droit',
    annee: 2019,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Magistrat',
  },
  {
    prenom: 'benito',
    nom: 'intello',
    promo: 'college de droit',
    annee: 2019,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'kevin',
    nom: 'le paresseux',
    promo: 'college de droit',
    annee: 2017,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Juriste',
  },
  {
    prenom: 'dave',
    nom: 'UFC',
    promo: 'college de droit',
    annee: 2016,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2015,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2014,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2020,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2021,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2020,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2019,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'test',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2018,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2021,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'ecole de droit',
    annee: 2021,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'ecole de droit',
    annee: 2019,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Notaire',
  },
  {
    prenom: 'mehdi ',
    nom: 'bekri',
    promo: 'ecole de droit',
    annee: 2020,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Magistrat',
  },
  {
    prenom: 'mehdi',
    nom: 'bekri',
    promo: 'college de droit',
    annee: 2018,
    photo: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    profession: 'Avocat',
  },
];

export default data;
